runtime: python38 # or another supported version
instance_class: F1 # this is the cheapest option
env_variables:
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: '12345'
  MYSQL_DB: 'team97_new'
  MYSQL_HOST: '35.232.147.201'
handlers:
- url: /script
  static_dir: static/script
- url: /styles
  static_dir: static/styles
- url: /img
  static_dir: static/img